---
- name: Netbox docker clone
  command: 'git clone -b release https://github.com/netbox-community/netbox-docker.git /home/cumulus/netbox-docker'

- name: Netbox initial config
  copy:
    src: netbox.env
    dest: /home/cumulus/netbox-docker/netbox.env 

- name: Netbox docker compose
  shell: 'cd /home/cumulus/netbox-docker;docker-compose pull;docker-compose up -d'

- name: Copy DB backup
  copy:
    src: netbox_postgres.sql
    dest: netbox_postgres.sql
    owner: cumulus
    group: cumulus
    mode: 0644

- name: Pause to let container start 
  pause:
    seconds: 120 

- name: Provision Netbox postgres db
  shell: 'cat netbox_postgres.sql | docker exec -i netboxdocker_postgres_1 psql -U postgres'
...
