---
- name: Create Ngrok dir
  file:
    path: /opt/ngrok
    state: directory
    mode: 0755

- name: Download Ngrok 
  get_url:
    url: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    dest: /opt/ngrok/ngrok-stable-linux-amd64.zip

- name: Unzip Ngrok 
  unarchive:
    src: /opt/ngrok/ngrok-stable-linux-amd64.zip
    dest: /opt/ngrok/ngrok
    remote_src: yes

- name: Delete Ngrok zip
  file:
    path: /opt/ngrok/ngrok-stable-linux-amd64.zip
    state: absent

- name: Copy ngrok config file 
  copy:
    src: ngrok.yml
    dest: /opt/ngrok.yml

- name: Copy Ngrok service
  copy:
    src: ngrok.service
    dest: /etc/systemd/system/ngrok.service

- name: Reload daemon
  command: systemctl daemon-reload

- name: Enable Ngrok daemon
  systemd:
    name: ngrok
    enabled: yes
...
