server01:
  id: 11
  ports:
    eth0:
      dhcp:
      vrf: mgmt
    eth1:
    eth2:
    uplink:
      lag:
      members:
        - eth1
        - eth2
  apps:
    1000:
      prefix-id: 10
      vrf: app1
    1001:
      prefix-id: 11
      vrf: app2
    1002:
      prefix-id: 12
      vrf: app3
    1003:
      prefix-id: 13
      vrf: app4
    1004:
      prefix-id: 14
      vrf: app5
    1005:
      prefix-id: 15
      vrf: app6

server02:
  id: 12
  ports:
    eth0:
      dhcp:
      vrf: mgmt
    eth1:
    eth2:
    uplink:
      lag:
      members:
        - eth1
        - eth2
  apps:
    1000:
      prefix-id: 10
      vrf: app1
    1001:
      prefix-id: 11
      vrf: app2
    1002:
      prefix-id: 12
      vrf: app3
    1003:
      prefix-id: 13
      vrf: app4
    1004:
      prefix-id: 14
      vrf: app5
    1005:
      prefix-id: 15
      vrf: app6
server05:
  id: 5
  ports:
    eth0:
      dhcp:
      vrf: mgmt
    eth1:
    eth2:
  tenants:
    tenant1:
      id: 4001
    tenant2:
      id: 4002
    tenant3:
      id: 4003
  l2domains:
    1000:
      prefix-id: 10
      tenant: tenant1
    1001:
      prefix-id: 11
      tenant: tenant1
    1002:
      prefix-id: 12
      tenant: tenant2
    1003:
      prefix-id: 13
      tenant: tenant2
    1004:
      prefix-id: 14
      tenant: tenant3
    1005:
      prefix-id: 15
      tenant: tenant3

server06:
  id: 6
  ports:
    eth0:
      dhcp:
      vrf: mgmt
    eth1:
    eth2:
  tenants:
    tenant1:
      id: 4001
    tenant2:
      id: 4002
    tenant3:
      id: 4003
  l2domains:
    1000:
      prefix-id: 10
      tenant: tenant1
    1001:
      prefix-id: 11
      tenant: tenant1
    1002:
      prefix-id: 12
      tenant: tenant2
    1003:
      prefix-id: 13
      tenant: tenant2
    1004:
      prefix-id: 14
      tenant: tenant3
    1005:
      prefix-id: 15
      tenant: tenant3
server09:
  id: 15
  ports:
    eth0:
      dhcp:
      vrf: mgmt
    eth1:
    eth2:
    uplink:
      lag:
      members:
        - eth1
        - eth2
  apps:
    1000:
      prefix-id: 10
      vrf: app1
    1001:
      prefix-id: 11
      vrf: app2
    1002:
      prefix-id: 12
      vrf: app3
    1003:
      prefix-id: 13
      vrf: app4
    1004:
      prefix-id: 14
      vrf: app5
    1005:
      prefix-id: 15
      vrf: app6

server10:
  id: 16
  ports:
    eth0:
      dhcp:
      vrf: mgmt
    eth1:
    eth2:
    uplink:
      lag:
      members:
        - eth1
        - eth2
  apps:
    1000:
      prefix-id: 10
      vrf: app1
    1001:
      prefix-id: 11
      vrf: app2
    1002:
      prefix-id: 12
      vrf: app3
    1003:
      prefix-id: 13
      vrf: app4
    1004:
      prefix-id: 14
      vrf: app5
    1005:
      prefix-id: 15
      vrf: app6
