devices:
  server01:
    id: 11
    ports:
      eth0:
        dhcp:
        vrf: mgmt
      eth1:
      eth2:
      uplink:
        lag:
        members:
          - eth1
          - eth2
    apps:
      1001:
        prefix-id: 11
        vrf: app1
      1002:
        prefix-id: 12
        vrf: app2
      1003:
        prefix-id: 13
        vrf: app3
      1004:
        prefix-id: 14
        vrf: app4
      1005:
        prefix-id: 15
        vrf: app5
      1006:
        prefix-id: 16
        vrf: app6

  server02:
    id: 12
    ports:
      eth0:
        dhcp:
        vrf: mgmt
      eth1:
      eth2:
      uplink:
        lag:
        members:
          - eth1
          - eth2
    apps:
      1001:
        prefix-id: 11
        vrf: app1
      1002:
        prefix-id: 12
        vrf: app2
      1003:
        prefix-id: 13
        vrf: app3
      1004:
        prefix-id: 14
        vrf: app4
      1005:
        prefix-id: 15
        vrf: app5
      1006:
        prefix-id: 16
        vrf: app6

  server03:
    id: 13
    ports:
      eth0:
        dhcp:
        vrf: mgmt
      eth1:
      eth2:
      uplink:
        lag:
        members:
          - eth1
          - eth2
    apps:
      1001:
        prefix-id: 11
        vrf: app1
      1002:
        prefix-id: 12
        vrf: app2
      1003:
        prefix-id: 13
        vrf: app3
      1004:
        prefix-id: 14
        vrf: app4
      1005:
        prefix-id: 15
        vrf: app5
      1006:
        prefix-id: 16
        vrf: app6

  server04:
    id: 14
    ports:
      eth0:
        dhcp:
        vrf: mgmt
      eth1:
      eth2:
    tenants:
      tenant1:
        id: 4001
      tenant2:
        id: 4002
      tenant3:
        id: 4003
    l2domains:
      1001:
        prefix-id: 11
        tenant: tenant1
      1002:
        prefix-id: 12
        tenant: tenant1
      1003:
        prefix-id: 13
        tenant: tenant2
      1004:
        prefix-id: 14
        tenant: tenant2
      1005:
        prefix-id: 15
        tenant: tenant3
      1006:
        prefix-id: 16
        tenant: tenant3

  server05:
    id: 15
    ports:
      eth0:
        dhcp:
        vrf: mgmt
      eth1:
      eth2:
      uplink:
        lag:
        members:
          - eth1
          - eth2
    apps:
      1001:
        prefix-id: 11
        vrf: app1
      1002:
        prefix-id: 12
        vrf: app2
      1003:
        prefix-id: 13
        vrf: app3
      1004:
        prefix-id: 14
        vrf: app4
      1005:
        prefix-id: 15
        vrf: app5
      1006:
        prefix-id: 16
        vrf: app6

  server06:
    id: 16
    ports:
      eth0:
        dhcp:
        vrf: mgmt
      eth1:
      eth2:
      uplink:
        lag:
        members:
          - eth1
          - eth2
    apps:
      1001:
        prefix-id: 11
        vrf: app1
      1002:
        prefix-id: 12
        vrf: app2
      1003:
        prefix-id: 13
        vrf: app3
      1004:
        prefix-id: 14
        vrf: app4
      1005:
        prefix-id: 15
        vrf: app5
      1006:
        prefix-id: 16
        vrf: app6

  server07:
    id: 17
    ports:
      eth0:
        dhcp:
        vrf: mgmt
      eth1:
      eth2:
      uplink:
        lag:
        members:
          - eth1
          - eth2
    apps:
      1001:
        prefix-id: 11
        vrf: app1
      1002:
        prefix-id: 12
        vrf: app2
      1003:
        prefix-id: 13
        vrf: app3
      1004:
        prefix-id: 14
        vrf: app4
      1005:
        prefix-id: 15
        vrf: app5
      1006:
        prefix-id: 16
        vrf: app6

  server08:
    id: 18
    ports:
      eth0:
        dhcp:
        vrf: mgmt
      eth1:
      eth2:
    tenants:
      tenant1:
        id: 4001
      tenant2:
        id: 4002
      tenant3:
        id: 4003
    l2domains:
      1001:
        prefix-id: 11
        tenant: tenant1
      1002:
        prefix-id: 12
        tenant: tenant1
      1003:
        prefix-id: 13
        tenant: tenant2
      1004:
        prefix-id: 14
        tenant: tenant2
      1005:
        prefix-id: 15
        tenant: tenant3
      1006:
        prefix-id: 16
        tenant: tenant3

  server09:
    id: 19
    ports:
      eth0:
        dhcp:
        vrf: mgmt
      eth1:
      eth2:
      uplink:
        lag:
        members:
          - eth1
          - eth2
    apps:
      1001:
        prefix-id: 11
        vrf: app1
      1002:
        prefix-id: 12
        vrf: app2
      1003:
        prefix-id: 13
        vrf: app3
      1004:
        prefix-id: 14
        vrf: app4
      1005:
        prefix-id: 15
        vrf: app5
      1006:
        prefix-id: 16
        vrf: app6

  server10:
    id: 20
    ports:
      eth0:
        dhcp:
        vrf: mgmt
      eth1:
      eth2:
      uplink:
        lag:
        members:
          - eth1
          - eth2
    apps:
      1001:
        prefix-id: 11
        vrf: app1
      1002:
        prefix-id: 12
        vrf: app2
      1003:
        prefix-id: 13
        vrf: app3
      1004:
        prefix-id: 14
        vrf: app4
      1005:
        prefix-id: 15
        vrf: app5
      1006:
        prefix-id: 16
        vrf: app6
