---
- name: Add Cumulus Apt Key
  apt_key:
    url: "https://apps3.cumulusnetworks.com/setup/cumulus-apps-deb.pubkey"
    state: present

- name: Add Cumulus Repo
  apt_repository:
    repo: deb https://apps3.cumulusnetworks.com/repos/deb xenial netq-2.1
    state: present
    update_cache: no

- name: Install NetQ
  apt:
    name: cumulus-netq
    update_cache: yes

- name: Add netq to mgmt vrf
  lineinfile:
    dest: /etc/vrf/systemd.conf
    line: "{{ item }}"
  with_items:
    - 'netq-agent'
    - 'netq-notifier'
    - 'netqd'

- name: Restart VRF systemctl daemon
  command: systemctl daemon-reload

- name: copy netq config file
  copy:
    src: netq.yml
    dest: /etc/netq/netq.yml

- name: Configure NetQ in management VRF
  command: "{{item}}"
  with_items:
    - systemctl stop netqd.service
    - systemctl disable netqd.service
    - systemctl stop netq-agent.service
    - systemctl disable netq-agent.service
    - systemctl enable netqd@mgmt
    - systemctl start netqd@mgmt
    - systemctl enable netq-agent@mgmt
    - systemctl start netq-agent@mgmt
  when: netq_installed.stdout.find('[installed]') == -1

- name: Restart Rsyslog
  service:
    name: rsyslog
    state: restarted
  when: netq_installed.stdout.find('[installed]') == -1
...
